# Generated by Django 2.2.17 on 2020-11-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20201110_1208"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dagfreagfc",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
