# Generated by Django 2.2.17 on 2020-11-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_dagfreagfc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dagfreagfc',
        ),
    ]
